# Generated by Django 5.0.1 on 2024-01-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='amount',
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('deliveryType', models.CharField(choices=[('IN', 'Indelivery'), ('OUT', 'Outdelivery')], max_length=3)),
                ('delivery_date', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.site')),
            ],
        ),
    ]
