# Generated by Django 5.0.1 on 2024-01-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_remove_storage_amount_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_date',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.storage'),
        ),
    ]
