# Generated by Django 5.0.1 on 2024-01-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_remove_delivery_delivery_date_alter_delivery_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
