# Generated by Django 5.0.1 on 2024-01-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_alter_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='date',
        ),
    ]
