# Generated by Django 5.0.1 on 2024-01-02 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
