# Generated by Django 5.0.1 on 2024-01-04 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0011_alter_delivery_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="amount",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
